name = "Polymetal Miata"
description = "All Polymetal_miata Mods are listed below"
keywords = "Mazda, Miata, MX-5, Polymetal"
image = "miata.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-FF7098W9XD"
base_url = "polymetal-miata.thewefactor.ca"


[[sections]]
title = "Modification List"
##description = "Most up-to-date list"
direction = "column"
item_style = "outline"

[[sections.items]]
title = "Borla S-Type Exhaust"
##description = "A mesmerizing thriller delving into the dark world of crime journalism"
url = "https://www.borla.com/products/mazda-mx-5-miata-axle-back-exhaust-system-11919/"

[[sections.items]]
title = "Konig Hypergram (Metallic Carbon W/ Machined Lip)"
##description = "A groundbreaking romantic drama challenging societal expectations"
url = "https://konigwheels.com/wheels/flow-formed-wheels/hypergram/"
[[sections.items]]
title = "Michelin Pilot Sport 4S Tires"
##description = "A gripping thriller entangling a detective in a web of secrets during a kidnapping investigation"
url = "https://www.michelin.ca/en/auto/tires/michelin-pilot-sport-4-s/"
[[sections.items]]
title = "FM corner light"
url = "https://flyinmiata.com/en-ca/products/variant-nd-corner-light-set?variant=43744892420351"
[[sections.items]]
title = "MX5things Dashcam cable"
url = "https://mx5things.com/en-ca/collections/mazda-mx-5-2016-nd-st/products/cable-for-plug-n-play-installation-blackvue-dashcam"
[[sections.items]]
title = "MX5things Airbag warning overlay"
url = "https://mx5things.com/en-ca/collections/mazda-mx-5-2016-nd-st/products/air-bag-warning-overlay-replacement"
[[sections.items]]
title = "MX5things DRL harness"
url = "https://mx5things.com/en-ca/collections/mazda-mx-5-2016-nd-st/products/drl-harness"
[[sections.items]]
title = "Cravenspeed Dipstick Handle"
url = "https://www.cravenspeed.com/the-dipstick-handle-for-mazda/"
[[sections.items]]
title = "Zunsport Full Lower Grille"
url = "https://www.zunsport.com/en/mazda-grilles/mazda-mx5-mk4-full-lower-grille"
[[sections.items]]
title = "TUXMAT Car Mats"
url = "https://www.tuxmat.ca/products/8474-mazda-mx-5-custom-mat?variant=40829812310148&year=2023&utm_campaign=&utm_source=adwords&utm_medium=ppc&utm_term=&hsa_ad=&hsa_src=x&hsa_grp=&hsa_net=adwords&hsa_kw=&hsa_acc=3526944315&hsa_cam=18798628745&hsa_tgt=&hsa_ver"
[[sections.items]]
title = "Sound Tube Delete"
url = "https://www.cravenspeed.com/sound-maker-delete-for-nd-miata/"
[[sections.items]]
title = "Stubby Antenna"
url = "https://www.cravenspeed.com/the-original-stubby-antenna-for-2016-2020-mazda-miata-mx-5/"
[[sections.items]]
title = "Oil Filler Cap"
url = "https://mazdashop.ca/collections/2016-2023-mx-5-all-products/products/oil-filler-cap-mx-5-mx-5-rf-2016-2023"
[[sections.items]]
title = "Cargo Tray"
url = "https://mazdashop.ca/collections/2016-2023-mx-5-all-products/products/cargo-tray-mazda-mx-5-mx-5-rf-2016-2023"
[[sections.items]]
title = "Lasfit MX-5 Miata LED Turn Signal"
url = "https://www.lasfit.com/products/2019-2020-mazda-mx-5-miata-led-turn-signal-backup-license-plate-light-bulbs"


[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/polymetal_miata"

