name = "Polymetal Miata"
description = "All Polymetal_miata Mods are listed below"
keywords = "Mazda, Miata, MX-5, Polymetal"
image = "miata.webp"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-33WB8LVHR6"


[[sections]]
title = "Modification List"
##description = "Most up-to-date list"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Borla S-Type Exhaust"
##description = "A mesmerizing thriller delving into the dark world of crime journalism"
url = "https://www.borla.com/products/mazda-mx-5-miata-axle-back-exhaust-system-11919/"
[[sections.items]]
title = "Konig Hypergram (Metallic Carbon W/ Machined Lip)"
##description = "A groundbreaking romantic drama challenging societal expectations"
url = "https://konigwheels.com/wheels/flow-formed-wheels/hypergram/"
[[sections.items]]
title = "Michelin Pilot Sport 4S Tires"
##description = "A gripping thriller entangling a detective in a web of secrets during a kidnapping investigation"
url = "https://www.michelin.ca/en/auto/tires/michelin-pilot-sport-4-s/"

[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/polymetal_miata"

